version: '3'
services:
    es:
        image: elasticsearch:8.11.0
        container_name: elasticsearch8.11
        privileged: true
        restart: unless-stopped
        environment:
            - node.name=es
            - cluster.name=elasticsearch
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - xpack.security.enabled=false
            - xpack.security.http.ssl.enabled=false
            - xpack.security.transport.ssl.enabled=false
        ports:
            - 9200:9200
            - 9300:9300
        ulimits:
            memlock:
                soft: -1
                hard: -1
    web:
        container_name: phpswoole
        image: phpswoole/swoole:5.0-php8.2
        ports:
            - "80:80"
        command: ["/bin/sh", "/sites/service/bash.sh"]
        links:
            - es
        depends_on:
            - es
        volumes:
            - ./service:/sites/service
